spring.application.name=vetcare

spring.datasource.url=jdbc:postgresql://localhost:5432/vetecare_db
spring.datasource.username=postgres
spring.datasource.password=Inge0925

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Clave secreta para firmar los JWT (en produccion iria en variable de entorno)
jwt.secret=EstaEsUnaClaveSecretaMuyLargaParaVetCare2026SeguridadJWT
# Duracion del token en milisegundos (aqui, 24 horas)
jwt.expiration=86400000